### ISSUE TITLE
Issue with programming the CPLD

### ISSUE THREAD

**Issue by timmcross** [LIV2/Bluster#9]
I have installed Buster-Lite on a RPi and when I try to run

sudo apt-get update

, it says

E: The repository 'https://apt.matrix.one/raspian buster Release' does not have a Release file.

and it won't allow updates from that repository.

Should I use buster or bullseye?  Is there something else I am missing?

Thanks...

**Comment by LIV2** [comment]
Hi,

I'm guessing they've removed Buster from their repo since I wrote the guide.
You should still be able to do it on Buster but it will need the additional step of compiling the software

Instructions on how to do that can be found here: https://linuxjedi.co.uk/2020/12/01/programming-xilinx-jtag-from-a-raspberry-pi/

**Comment by timmcross** [comment]
Ah, that could be it.  Thanks for the reply.  I ended up doing just that and it seemed using matrix_creator instead of sysfsgpio_creator worked for me.  Great work!
